### ISSUE TITLE
Need to support new instance type Enterprise and Standard and corresponding volume type

### ISSUE THREAD

**Issue by zryfish** [yunify/qingcloud-sdk-go#118]
**Enterprise** and **Standard** instance type support needed, our [csi plugin](https://github.com/yunify/qingcloud-csi) depends on this feature.

[RunInstances](https://github.com/yunify/qingcloud-sdk-go/blob/master/service/instance.go#L672)
[Volumes](https://github.com/yunify/qingcloud-sdk-go/blob/master/service/volume.go#L151)

**Comment by huyujie** [comment]
#119 fixed.
