### ISSUE TITLE
部分资源缺少 tags 字段

### ISSUE THREAD

**Issue by lowstz** [yunify/qingcloud-sdk-go#12]
Router 
Mongo
S2Server
SecurityGroup

比如 [router](https://github.com/yunify/qingcloud-sdk-go/blob/master/service/types.go#L1774) 调用 DescribeRouter 返回结果有 tags 字段
``` json
{
  "action": "DescribeRoutersResponse",
  "router_set": [
    {
      "status": "active",
      "base_vxnet": "",
      "is_applied": 1,
      "features": 0,
      "vpc_network": "192.168.0.0/16",
      "create_time": "2017-03-17T09:51:03Z",
      "alarm_status": "",
      "private_ip": "10.120.25.39",
      "owner": "usr-dD0cnWpH",
      "vxnets": [
        {
          "nic_id": "",
          "vxnet_id": "vxnet-0"
        }
      ],
      "sub_code": 0,
      "security_group_id": "sg-rvb00rki",
      "status_time": "2017-03-17T09:51:10Z",
      "router_id": "rtr-3plztw26",
      "description": null,
      "tags": [
        {
          "color": "green",
          "tag_name": "test",
          "tag_key": "default",
          "tag_id": "tag-76x7l3w6"
        }
      ],
      "transition_status": "",
      "vpc_id": "vpc-0556uz60",
      "eip": {
        "eip_name": "",
        "eip_addr": "",
        "eip_id": ""
      },
      "dns_aliases": [],
      "router_type": 1,
      "router_name": "test"
    }
  ],
  "total_count": 1,
  "ret_code": 0
}
```

**Comment by pengsrc** [comment]
感谢反馈，由于 SDK 的 Service 调用部分的代码是根据 API Specs 生成的，但是目前 IaaS 的 API Specs 还需要一些整理和校对，所以生成出来的代码和实际使用会有稍许偏差。IaaS 的 API Specs 会在稍后公布出来，遇到类似问题您先可以暂时修改本地依赖的 SDK 代码，增加 struct 中缺少的字段。给您造成的不便敬请谅解，这个 Issue 会在问题解决之前保留成 Open。

这里描述了我们的 SDK 开发流程，https://github.com/yunify/snips，供参考。

**Comment by lowstz** [comment]
@pengsrc  

IaaS 的 API Specs 公布有进展吗，我又遇到一堆文档混乱的 API。
比如 security_group_rule 相关里面相同字段，不同 API 里类型不一样， integer 和 string 混用。

**Comment by Sunight** [comment]
你好，我们已安排人手 review 文档，逐渐修正 Specs 。

**Comment by Sunight** [comment]
争取月底前完成

**Comment by lowstz** [comment]
@Sunight  有进度吗？

**Comment by Sunight** [comment]
还在 review 中，下周差不多了

**Comment by lowstz** [comment]
@Sunight  现在什么情况，各位大哥们 😨

**Comment by phantooom** [comment]
@lowstz 你好这边的 security_group_rule 这个字段只有  DescribeSecurityGroupRules 才会返回的，里面的val[n] 都是字符串类型的并没有问题，具体您说的其他api返回，可以举一下例子，其他的缺少的tag的api我们这边已经开始加入了，近期就会重新生成一遍SDK。

**Comment by martinyunify** [comment]
#28  添加了router 和security group的tags.

**Comment by cygnushan** [comment]
https://github.com/yunify/qingcloud-api-specs/pull/2/
添加了vxnet和s2_shared_target的tags
