### ISSUE TITLE
cannot unmarshal object into Go struct field Cluster.upgrade_policy of type string

### ISSUE THREAD

**Issue by huangwind205** [yunify/qingcloud-sdk-go#144]
UpgradePolicy              []* string    `json:"upgrade_policy" name:"upgrade_policy"`
这儿有点问题, 改成下面的比较合适吧
UpgradePolicy              []* interface{}    `json:"upgrade_policy" name:"upgrade_policy"`

**Comment by xiaoxiaolele** [comment]
#145 has resolved this issue.
