### ISSUE TITLE
最好开放查询虚拟机接口

### ISSUE THREAD

**Issue by knightXun** [yunify/qingcloud-sdk-go#17]
client.go中的QingCloudClient不支持直接查询虚拟机，DescribeInstance勉强可以算作一个，但提供的过滤条件太少．最好新增加接口直接查询主机．

**Comment by pengsrc** [comment]
可以使用这个来查询主机，有所有 API 支持的过滤条件，https://github.com/yunify/qingcloud-sdk-go/blob/master/service/instance.go#L93-L185

**Comment by knightXun** [comment]
多谢
