### ISSUE TITLE
openstack和qingcloud删除loadbalancer的区别

### ISSUE THREAD

**Issue by knightXun** [yunify/qingcloud-sdk-go#18]
我注意到openstack删除loadbalance的过程相当繁琐：想要删除相关的monitor,然后是pool，接下来是Security Group，最后是删除LoadBalancer自己．请问qingcloud在这方面有什么不同？

**Comment by knightXun** [comment]
@pengsrc

**Comment by pengsrc** [comment]
直接使用 DeleteLoadBalancers 这个 API 删除 LB 就可以。

参见：https://github.com/yunify/qingcloud-sdk-go/blob/master/service/load_balancer.go#L717-L765

**Comment by knightXun** [comment]
这个issue先别关

**Comment by jolestar** [comment]
Security Group 还是要自己删除的。

**Comment by martinyunify** [comment]
已经过去两个月了．如果需要请再打开． @knightXun

**Comment by knightXun** [comment]
多谢了
