### ISSUE TITLE
什么时候会发一个新版呢？

### ISSUE THREAD

**Issue by martinyunify** [yunify/qingcloud-sdk-go#22]
发现使用glide下下来的最新release版不包含nic操作的api. 
能不能帮忙发个新版好吗

**Comment by pengsrc** [comment]
是说通过指定 Tag 吗？可以暂时用 master 最新的 commit，我发一下版本

**Comment by pengsrc** [comment]
新版已发布 https://github.com/yunify/qingcloud-sdk-go/releases/tag/v2.0.0-alpha.6
