### ISSUE TITLE
CreateMongoInput's feild  MongoVersion shouldn's be *int,it's should be *string or string type

### ISSUE THREAD

**Issue by huangjiasingle** [yunify/qingcloud-sdk-go#24]
when l use the sdk to create mongDB, if the CreateMongoInput's feild  MongoVersion is *int, l could create mongoDB succes, so l modified it to *string, it's ok.

**Comment by martinyunify** [comment]
I'm wondering why I should change the type of MongoVersion since you can create mongodb successfully
