### ISSUE TITLE
提个小建议：你们内部的开发需要规范下

### ISSUE THREAD

**Issue by huangjiasingle** [yunify/qingcloud-sdk-go#49]
原因如下：获取RDB，mongo，cache的监控数据，mongo返回的json中 数据在 data字段，而其他返回的数据在data_set字段，还有很多struct中的定义的字端缺少，或者多了很多类型不对的！

**Comment by jolestar** [comment]
不好意思，这个问题是 api 的历史遗留问题，我们新版的应用都迁移到 appcenter 上去了，以后所有的应用输出的格式都会是统一的。感谢反馈。

**Comment by huangjiasingle** [comment]
@jolestar 多谢！
