### ISSUE TITLE
Lack of quota api and gpu parameter when RunInstance

### ISSUE THREAD

**Issue by chilianyi** [yunify/qingcloud-sdk-go#99]
I have not find GetQuotaLeft api: https://docs.qingcloud.com/product/api/action/misc/get_quota_left.html
No Gpu parameter when call RunInstance: https://docs.qingcloud.com/product/api/action/instance/run_instances.html

**Comment by huyujie** [comment]
I have already added in #100. Hopefully,it will be merged into master in tomorrow.

**Comment by chilianyi** [comment]
Thanks

**Comment by Sunight** [comment]
fixed in #100
